.TH HELLODEB 1 "21 April 2022" "hellodeb"
.SH NAME
hellodeb \- print hello deb
.SH SYNOPSIS
hellodeb
.SH DESCRIPTION
hellodeb is an hello program to demonstrate Debian packaging.
.SH OPTIONS
hellodeb does not take any options.
.SH SEE ALSO
dpkg-buildpackage(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Mete Balci (metebalci@gmail.com)
